// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeouHZYqUBc_WOe0fRtM0sSY33lD4RmlA',
    appId: '1:545592204516:web:419cfedf1646640411e0f1',
    messagingSenderId: '545592204516',
    projectId: 'bakeryapp-b0e1d',
    authDomain: 'bakeryapp-b0e1d.firebaseapp.com',
    storageBucket: 'bakeryapp-b0e1d.appspot.com',
    measurementId: 'G-7Z4P9E2TM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBhwcrQKSsHQng-MDW0hanf-KS3dPzaE',
    appId: '1:545592204516:android:2f1e2ae5f7959b3211e0f1',
    messagingSenderId: '545592204516',
    projectId: 'bakeryapp-b0e1d',
    storageBucket: 'bakeryapp-b0e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBstfuuw5BFLMIKdZVQ9ZIGYGTL_lOKVyM',
    appId: '1:545592204516:ios:a6f941db1f48eca011e0f1',
    messagingSenderId: '545592204516',
    projectId: 'bakeryapp-b0e1d',
    storageBucket: 'bakeryapp-b0e1d.appspot.com',
    iosBundleId: 'com.example.bakeryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBstfuuw5BFLMIKdZVQ9ZIGYGTL_lOKVyM',
    appId: '1:545592204516:ios:a6f941db1f48eca011e0f1',
    messagingSenderId: '545592204516',
    projectId: 'bakeryapp-b0e1d',
    storageBucket: 'bakeryapp-b0e1d.appspot.com',
    iosBundleId: 'com.example.bakeryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeouHZYqUBc_WOe0fRtM0sSY33lD4RmlA',
    appId: '1:545592204516:web:d8f4ce8e04f9e85d11e0f1',
    messagingSenderId: '545592204516',
    projectId: 'bakeryapp-b0e1d',
    authDomain: 'bakeryapp-b0e1d.firebaseapp.com',
    storageBucket: 'bakeryapp-b0e1d.appspot.com',
    measurementId: 'G-GX68SBZJSE',
  );
}
